// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v1.8.1
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:426


#include "MountVertexLLamaC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/AnyTypeCode/String_TypeCode_Static.h"
#include "tao/CDR.h"
#include "tao/Object_T.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "MountVertexLLamaC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for Control::MountVertexLLama.

Control::MountVertexLLama_ptr
TAO::Objref_Traits<Control::MountVertexLLama>::duplicate (
    Control::MountVertexLLama_ptr p)
{
  return Control::MountVertexLLama::_duplicate (p);
}

void
TAO::Objref_Traits<Control::MountVertexLLama>::release (
    Control::MountVertexLLama_ptr p)
{
  ::CORBA::release (p);
}

Control::MountVertexLLama_ptr
TAO::Objref_Traits<Control::MountVertexLLama>::nil (void)
{
  return Control::MountVertexLLama::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Control::MountVertexLLama>::marshal (
    const Control::MountVertexLLama_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// Function pointer for collocation factory initialization.
TAO::Collocation_Proxy_Broker * 
(*Control__TAO_MountVertexLLama_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj) = 0;

Control::MountVertexLLama::MountVertexLLama (void)
 : the_TAO_MountVertexLLama_Proxy_Broker_ (0)
{
  this->Control_MountVertexLLama_setup_collocation ();
}

void
Control::MountVertexLLama::Control_MountVertexLLama_setup_collocation ()
{
  if (::Control__TAO_MountVertexLLama_Proxy_Broker_Factory_function_pointer)
    {
      this->the_TAO_MountVertexLLama_Proxy_Broker_ =
        ::Control__TAO_MountVertexLLama_Proxy_Broker_Factory_function_pointer (this);
    }
  
  this->Control_MountVertexLLamaBase_setup_collocation ();
}

Control::MountVertexLLama::~MountVertexLLama (void)
{}

void 
Control::MountVertexLLama::_tao_any_destructor (void *_tao_void_pointer)
{
  MountVertexLLama *_tao_tmp_pointer =
    static_cast<MountVertexLLama *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

Control::MountVertexLLama_ptr
Control::MountVertexLLama::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<MountVertexLLama>::narrow (
        _tao_objref,
        "IDL:alma/Control/MountVertexLLama:1.0",
        Control__TAO_MountVertexLLama_Proxy_Broker_Factory_function_pointer
      );
}

Control::MountVertexLLama_ptr
Control::MountVertexLLama::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<MountVertexLLama>::unchecked_narrow (
        _tao_objref,
        "IDL:alma/Control/MountVertexLLama:1.0",
        Control__TAO_MountVertexLLama_Proxy_Broker_Factory_function_pointer
      );
}

Control::MountVertexLLama_ptr
Control::MountVertexLLama::_duplicate (MountVertexLLama_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  
  return obj;
}

void
Control::MountVertexLLama::_tao_release (MountVertexLLama_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Control::MountVertexLLama::_is_a (const char *value)
{
  if (
      !ACE_OS::strcmp (
          value,
          "IDL:alma/ACS/ACSComponent:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:alma/ACS/CharacteristicModel:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:alma/ACS/CharacteristicComponent:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:alma/Control/ControlDevice:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:alma/Control/HardwareDevice:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:alma/Control/MountBase:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:alma/Control/Mount:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:alma/Control/MountVertexBase:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:alma/Control/MountVertex:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:alma/Control/MountVertexLLamaBase:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:alma/Control/MountVertexLLama:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* Control::MountVertexLLama::_interface_repository_id (void) const
{
  return "IDL:alma/Control/MountVertexLLama:1.0";
}

::CORBA::Boolean
Control::MountVertexLLama::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/objref_typecode.cpp:76

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_Control_MountVertexLLama (
    ::CORBA::tk_objref,
    "IDL:alma/Control/MountVertexLLama:1.0",
    "MountVertexLLama");
  

namespace Control
{
  ::CORBA::TypeCode_ptr const _tc_MountVertexLLama =
    &_tao_tc_Control_MountVertexLLama;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_cs.cpp:49
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<Control::MountVertexLLama>::to_object (
      ::CORBA::Object_ptr &_tao_elem
    ) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Control
{
  
  
  /// Copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      MountVertexLLama_ptr _tao_elem)
  {
    MountVertexLLama_ptr _tao_objptr =
      MountVertexLLama::_duplicate (_tao_elem);
    _tao_any <<= &_tao_objptr;
  }
  
  /// Non-copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      MountVertexLLama_ptr *_tao_elem)
  {
    TAO::Any_Impl_T<MountVertexLLama>::insert (
        _tao_any,
        MountVertexLLama::_tao_any_destructor,
        _tc_MountVertexLLama,
        *_tao_elem)
  }
  
  ::CORBA::Boolean
  operator>>= (
      const ::CORBA::Any &_tao_any,
      MountVertexLLama_ptr &_tao_elem)
  {
    return
      TAO::Any_Impl_T<MountVertexLLama>::extract (
          _tao_any,
          MountVertexLLama::_tao_any_destructor,
          _tc_MountVertexLLama,
          _tao_elem)
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    Control::MountVertexLLama_ptr _tao_elem)
{
  Control::MountVertexLLama_ptr _tao_objptr =
    Control::MountVertexLLama::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    Control::MountVertexLLama_ptr *_tao_elem)
{
  TAO::Any_Impl_T<Control::MountVertexLLama>::insert (
      _tao_any,
      Control::MountVertexLLama::_tao_any_destructor,
      Control::_tc_MountVertexLLama,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    Control::MountVertexLLama_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<Control::MountVertexLLama>::extract (
        _tao_any,
        Control::MountVertexLLama::_tao_any_destructor,
        Control::_tc_MountVertexLLama,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_cs.cpp:54

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Control::MountVertexLLama_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Control::MountVertexLLama_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;
  
  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::Control::MountVertexLLama RHS_SCOPED_NAME;
  
  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        Control__TAO_MountVertexLLama_Proxy_Broker_Factory_function_pointer
      );
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



