// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v1.8.1
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:149

#ifndef _TAO_IDL__TMP__MOUNTVERTEXLLAMABASEC_H_
#define _TAO_IDL__TMP__MOUNTVERTEXLLAMABASEC_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/AnyTypeCode/TypeCode.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/String_Manager_T.h"
#include "tao/Objref_VarOut_T.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "HardwareDeviceC.h"
#include "ControlExceptionsC.h"
#include "baciC.h"
#include "MountVertexC.h"

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from 
// be/be_visitor_root/root_ch.cpp:151
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  class Collocation_Proxy_Broker;
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:41

namespace Control
{
  
  // TAO_IDL - Generated from
  // be/be_interface.cpp:785

#if !defined (_CONTROL_MOUNTVERTEXLLAMABASE__VAR_OUT_CH_)
#define _CONTROL_MOUNTVERTEXLLAMABASE__VAR_OUT_CH_
  
  class MountVertexLLamaBase;
  typedef MountVertexLLamaBase *MountVertexLLamaBase_ptr;
  
  typedef
    TAO_Objref_Var_T<
        MountVertexLLamaBase
      >
    MountVertexLLamaBase_var;
  
  typedef
    TAO_Objref_Out_T<
        MountVertexLLamaBase
      >
    MountVertexLLamaBase_out;

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:45
  
  class  MountVertexLLamaBase
    : public virtual ::Control::MountVertex
  {
  public:
    friend class TAO::Narrow_Utils<MountVertexLLamaBase>;
    typedef MountVertexLLamaBase_ptr _ptr_type;
    typedef MountVertexLLamaBase_var _var_type;
    typedef MountVertexLLamaBase_out _out_type;
    
    // The static operations.
    static MountVertexLLamaBase_ptr _duplicate (MountVertexLLamaBase_ptr obj);
    
    static void _tao_release (MountVertexLLamaBase_ptr obj);
    
    static MountVertexLLamaBase_ptr _narrow (::CORBA::Object_ptr obj);
    static MountVertexLLamaBase_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static MountVertexLLamaBase_ptr _nil (void)
    {
      return static_cast<MountVertexLLamaBase_ptr> (0);
    }
    
    static void _tao_any_destructor (void *);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROlongSeq_ptr
    METR_DELTAS_DISP (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROlongSeq_ptr
    METR_DELTAS_SPEM (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROlongSeq_ptr
    METR_DELTAS_TILT (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROlongSeq_ptr
    METR_DELTAS_TILTTEMP (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROlongSeq_ptr
    METR_TEMPS_19 (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROlongSeq_ptr
    METR_TEMPS_1A (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROlongSeq_ptr
    METR_TEMPS_1B (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROlongSeq_ptr
    METR_TEMPS_1C (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROlongSeq_ptr
    METR_TEMPS_1D (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROlongSeq_ptr
    METR_TEMPS_1E (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROlongSeq_ptr
    METR_TEMPS_1F (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROlongSeq_ptr
    SUBREF_DELTA_ROT (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROpattern_ptr
    OTHER_STATUS (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROpattern_ptr
    UPS2_ALARMS (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROlongSeq_ptr
    UPS2_BATTERY_OUTPUT (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROlongSeq_ptr
    UPS2_BATTERY_STATUS (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROlongSeq_ptr
    UPS2_BYPASS_VOLTS (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROlongSeq_ptr
    UPS2_FREQS (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROlong_ptr
    UPS1_INVERTER_SW (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROlong_ptr
    UPS2_INVERTER_SW (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROlongSeq_ptr
    UPS2_INVERTER_VOLTS (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROlongSeq_ptr
    UPS2_OUTPUT_CURRENT (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROlongSeq_ptr
    UPS2_OUTPUT_VOLTS (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROlong_ptr
    UPS_STATUS_1 (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::ACS::ROlong_ptr
    UPS_STATUS_2 (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::CORBA::Boolean
    GET_EMERGENCY_STOP_AZ_DRIVES_EQUIP_CONTAINER (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::CORBA::Boolean
    GET_EMERGENCY_STOP_PLATFORM_2_RECV_CABIN (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::CORBA::Boolean
    GET_EMERGENCY_STOP_NASMYTH_CABINS_AB (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::CORBA::Boolean
    GET_EMERGENCY_STOP_ACESS_TO_PLATFORM_OUTSIDE_PEDESTAL (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::CORBA::Boolean
    GET_EMERGENCY_STOP_CONTROL_CONTAINER (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::CORBA::Boolean
    GET_COMMUNICATION_ERROR_ACU_UPS2 (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::Control::LongSeq *
    GET_METR_DELTAS_DISP (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::Control::LongSeq *
    GET_METR_DELTAS_SPEM (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::Control::LongSeq *
    GET_METR_DELTAS_TILT (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::Control::LongSeq *
    GET_METR_DELTAS_TILTTEMP (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::Control::LongSeq *
    GET_METR_TEMPS_19 (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::Control::LongSeq *
    GET_METR_TEMPS_1A (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::Control::LongSeq *
    GET_METR_TEMPS_1B (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::Control::LongSeq *
    GET_METR_TEMPS_1C (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::Control::LongSeq *
    GET_METR_TEMPS_1D (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::Control::LongSeq *
    GET_METR_TEMPS_1E (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::Control::LongSeq *
    GET_METR_TEMPS_1F (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::Control::LongSeq *
    GET_SUBREF_DELTA_ROT (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::CORBA::Long
    GET_OTHER_STATUS (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::Control::LongSeq *
    GET_UPS2_ALARMS (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::Control::LongSeq *
    GET_UPS2_BATTERY_OUTPUT (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::Control::LongSeq *
    GET_UPS2_BATTERY_STATUS (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::Control::LongSeq *
    GET_UPS2_BYPASS_VOLTS (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::Control::LongSeq *
    GET_UPS2_FREQS (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::CORBA::Long
    GET_UPS1_INVERTER_SW (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::CORBA::Long
    GET_UPS2_INVERTER_SW (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::Control::LongSeq *
    GET_UPS2_INVERTER_VOLTS (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::Control::LongSeq *
    GET_UPS2_OUTPUT_CURRENT (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::Control::LongSeq *
    GET_UPS2_OUTPUT_VOLTS (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::CORBA::Long
    GET_UPS_STATUS_1 (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual ::CORBA::Long
    GET_UPS_STATUS_2 (
      ::ACS::Time_out timestamp);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual void
    SET_SUBREF_DELTA_ROT (
      const ::Control::LongSeq & world);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:36
    
    virtual void
    SET_SELFTEST_STOP (void);
    
    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:204
    
    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  private:
    TAO::Collocation_Proxy_Broker *the_TAO_MountVertexLLamaBase_Proxy_Broker_;
  
  protected:
    // Concrete interface only.
    MountVertexLLamaBase (void);
    
    // These methods traverse the inheritance tree and set the
    // parents piece of the given class in the right mode.
    virtual void Control_MountVertexLLamaBase_setup_collocation (void);
    
    // Concrete non-local interface only.
    MountVertexLLamaBase (
        ::IOP::IOR *ior,
        TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    MountVertexLLamaBase (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = 0,
        TAO_ORB_Core *orb_core = 0);
    
    virtual ~MountVertexLLamaBase (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    MountVertexLLamaBase (const MountVertexLLamaBase &);
    
    void operator= (const MountVertexLLamaBase &);
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:39
  
  extern  ::CORBA::TypeCode_ptr const _tc_MountVertexLLamaBase;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:70

} // module Control

// Proxy Broker Factory function pointer declarations.

// TAO_IDL - Generated from
// be/be_visitor_root/root_ch.cpp:193

extern 
TAO::Collocation_Proxy_Broker *
(*Control__TAO_MountVertexLLamaBase_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj);

// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:60

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_CONTROL_MOUNTVERTEXLLAMABASE__TRAITS_)
#define _CONTROL_MOUNTVERTEXLLAMABASE__TRAITS_
  
  template<>
  struct  Objref_Traits< ::Control::MountVertexLLamaBase>
  {
    static ::Control::MountVertexLLamaBase_ptr duplicate (
        ::Control::MountVertexLLamaBase_ptr p);
    static void release (
        ::Control::MountVertexLLamaBase_ptr p);
    static ::Control::MountVertexLLamaBase_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Control::MountVertexLLamaBase_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:45



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Control
{
   void operator<<= ( ::CORBA::Any &, MountVertexLLamaBase_ptr); // copying
   void operator<<= ( ::CORBA::Any &, MountVertexLLamaBase_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, MountVertexLLamaBase_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, Control::MountVertexLLamaBase_ptr); // copying
 void operator<<= (::CORBA::Any &, Control::MountVertexLLamaBase_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Control::MountVertexLLamaBase_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_ch.cpp:46

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Control::MountVertexLLamaBase_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, Control::MountVertexLLamaBase_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1786
#if defined (__ACE_INLINE__)
#include "MountVertexLLamaBaseC.inl"
#endif /* defined INLINE */

#endif /* ifndef */

